version: "3"

services:
  # configuration server
  configSrv:
    image: mongo:latest
    container_name: configSrv
    command: mongod --configsvr --replSet config_server --bind_ip_all --port 27017
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1:
    image: mongo:latest
    container_name: shard1
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - shard1-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2:
    image: mongo:latest
    container_name: shard2
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    restart: always
    ports:
      - "27019:27019"
    volumes:
      - shard2-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    command: mongos --configdb config_server/configSrv:27017 --bind_ip_all --port 27020
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
      - shard2
      - shard1
      - configSrv
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"

volumes:
  config-data:
  shard1-data:
  shard2-data:
