version: "3"

services:
  ########################
  # Configuration Server #
  ########################
  configSrv:
    image: mongo:latest
    container_name: configSrv
    command: mongod --configsvr --replSet config_server --bind_ip_all --port 27017
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  ########################
  # Shard 1              #
  ########################
  shard1_repl1:
    image: mongo:latest
    container_name: shard1_repl1
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    restart: always
    volumes:
      - shard1-repl1-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1_repl2:
    image: mongo:latest
    container_name: shard1_repl2
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    restart: always
    volumes:
      - shard1-repl2-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1_repl3:
    image: mongo:latest
    container_name: shard1_repl3
    command: mongod --shardsvr --replSet shard1 --bind_ip_all --port 27018
    restart: always
    volumes:
      - shard1-repl3-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  ########################
  # Shard 2              #
  ########################
  shard2_repl1:
    image: mongo:latest
    container_name: shard2_repl1
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    restart: always
    volumes:
      - shard2-repl1-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2_repl2:
    image: mongo:latest
    container_name: shard2_repl2
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    restart: always
    volumes:
      - shard2-repl2-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2_repl3:
    image: mongo:latest
    container_name: shard2_repl3
    command: mongod --shardsvr --replSet shard2 --bind_ip_all --port 27019
    restart: always
    volumes:
      - shard2-repl3-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  ########################
  # Router               #
  ########################
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27020:27020"
    command: mongos --configdb config_server/configSrv:27017 --bind_ip_all --port 27020
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  ########################
  # Cache - Redis        #
  ########################
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  ########################
  # App                  #
  ########################
  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
      - shard2_repl1
      - shard2_repl2
      - shard2_repl3
      - shard1_repl1
      - shard1_repl2
      - shard1_repl3
      - configSrv
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos_router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis:6379"

volumes:
  config-data:
  shard1-repl1-data:
  shard1-repl2-data:
  shard1-repl3-data:
  shard2-repl1-data:
  shard2-repl2-data:
  shard2-repl3-data:
  redis_data:
